language: java
jdk:
  - openjdk8

sudo: false

install:
  - cd e1interview/ && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd ../e2interview/ && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#Init X Virtual Framebuffer
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
- cd e1interview/ && mvn test -B
- cd ../e2interview/ && mvn test -B